# -*- coding: utf-8 -*-
"""SAF AI Model exp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11KUeg_G8GsPYH57gTiPDkKFeBhfrcuNI
"""

!pip install pandas numpy scikit-learn --quiet

import pandas as pd
import numpy as np
import random

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

users = pd.read_csv("gym_members_exercise_tracking.csv")
exercises = pd.read_csv("megaGymDataset.csv")

users["BMI"] = users["Weight (kg)"] / (users["Height (m)"] ** 2)

X = users[[
"Age",
"Weight (kg)",
"Height (m)",
"BMI",
"Workout_Frequency (days/week)"
]]

y = users["Experience_Level"]

encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

X_train,X_test,y_train,y_test = train_test_split(
X,
y_encoded,
test_size=0.2,
random_state=42
)

model = RandomForestClassifier(
n_estimators=300,
max_depth=12,
random_state=42
)

model.fit(X_train,y_train)

pred = model.predict(X_test)

print("Model Accuracy:",accuracy_score(y_test,pred))

strength_exercises = exercises[
exercises["Type"] == "Strength"
]

def filter_injuries(exercises, injury):

    if injury == "knee":
        avoid = ["Squat","Lunge"]

    elif injury == "shoulder":
        avoid = ["Overhead"]

    elif injury == "back":
        avoid = ["Deadlift"]

    else:
        return exercises

    filtered = exercises[
        ~exercises["Title"].str.contains("|".join(avoid), case=False)
    ]

    return filtered

def generate_workout(level, days, injury):

    available_exercises = filter_injuries(strength_exercises,injury)

    exercise_list = available_exercises["Title"].dropna().tolist()

    if level == 0:
        reps = "3 x 10"
    elif level == 1:
        reps = "4 x 8"
    else:
        reps = "5 x 5"

    workout_plan = {}

    for d in range(days):

        chosen = random.sample(exercise_list,5)

        workout_plan[f"Day {d+1}"] = [
            f"{ex} {reps}" for ex in chosen
        ]

    return workout_plan

age = int(input("Enter your age: "))
weight = float(input("Enter your weight (kg): "))
height = float(input("Enter your height (m): "))
days = int(input("Workout days per week: "))
injury = input("Any injury? (none/knee/shoulder/back): ")

bmi = weight / (height**2)

user = [[age,weight,height,bmi,days]]

level = model.predict(user)[0]

level_name = encoder.inverse_transform([level])[0]

plan = generate_workout(level,days,injury)

print("\nPredicted Fitness Level:",level_name)

print("\nYour Workout Plan:\n")

for day, exercises in plan.items():

    print(day)

    for ex in exercises:
        print("-",ex)

    print()